language: python
python:
  - "3.6"
before_install:
  - export DJANGO_SETTINGS_MODULE=spc_django.settings
install:
  - pip3 install -r requirements.txt
script:
  - cp .env.example .env
  - cd src
  - flake8 .
  - python3 manage.py collectstatic
  - python3 manage.py makemigrations student
  - python3 manage.py migrate student
  - python3 manage.py makemigrations
  - python3 manage.py migrate